var binatang = ["anjing", "panda", "kucing", "singa", "harimau", "gajah", "ular"];
console.log(binatang[2]);

// (BINATANG[2]) INI DIGUNAKAN UNTUK MENANMPILKAN ARRAY KE 2 DARI VAR BINATANG
console.log(binatang.length);
// LENGTH INI DIGUNAKAN UNTUK ADA BERAPA JUMLAH DARI ELEMEN VARIABEL BINATANG

// console.log(typeof binatang);
// TYPENYA BUKAN ARRAY TAPI OBJECT TIDAK ADA TYPE ARRAY MELAINKAN TYPE OBJECT

/* JAVASCRIPT DIMULAI DARI 0 BUKAN DARI 1 DAN UNTUK ARRAY MENGGUNAKAN [INI UNTUK ARRAY] DAN {BUKAN PAKAI INI } */

// ARAAY INI BISA DIGUNAKAN BOLEH BEDA TIPE CONTOHNYA ANGKA(INTEGER), KALIMAT (STRING) , DAN JUGA BOLEH BOOLEAN (TRUE / FALSE)

/* INI CONTOH ARRAY BERSARANG ATAU BERDIMENSI */
/* var myArr3 = ["teks", 2, false, [1, 2, 3], ["mahesa", 15, true]];

console.log(myArr3[4][0]);
console.log(myArr3[4][1]); */

// PENGGUNAAN ARRYA BERSARANG ATAU BERDIMENSI YANG BERBEDA TYPE ADA STRING,INTEGER,BOOLEAN DAN JUGA BISA MEMASUKAN BANYAK DATA DI 1 ARRAY
